/**
 * `monday board group-duplicate <bid> <gid> [--name <n>]
 * [--dry-run]` — duplicate a group on a board (`cli-design.md`
 * §4.3 line 1441, `v0.2-plan.md` §3 M17).
 *
 * **Wire shape.** Single round-trip via `duplicate_group(board_id,
 * group_id, add_to_top?, group_title?)` per SDK 14.0.0
 * `MutationDuplicate_GroupArgs`. Returns `Maybe<Group>` (the
 * newly-duplicated group, with a fresh ID auto-generated by
 * Monday). `--name <n>` maps to wire `group_title?` (when omitted,
 * Monday's wire-side default naming applies — typically
 * `"<source name> (copy)"`, but the exact convention is server-
 * side, not pinned by the CLI). M17 deliberately OMITS
 * `add_to_top: Boolean` — agents needing placement control call
 * the wire mutation via M9's `dev mutate` escape hatch (mirrors
 * M16 column-create's omission of `after_column_id`).
 *
 * **Load-bearing divergence from sibling duplicate verbs.** `monday
 * item duplicate` and `monday board duplicate` both surface
 * `--with-updates` (mapping to wire `with_updates: Boolean` on
 * `duplicate_item` / `duplicate_board`); `monday board group-
 * duplicate` does NOT, because Monday's `duplicate_group` wire
 * signature has no equivalent argument. The pre-pre-flight
 * v0.2-plan §3 M17 draft listed `[--with-updates]` for group-
 * duplicate; the M17 pre-flight pinned the wire truth and dropped
 * the flag.
 *
 * **Live-envelope projection.** Returned `Maybe<Group>` is
 * projected through `groupProjectionSchema` via
 * `projectMutationGroup`. The CLI's success envelope's `data` is
 * the new group's projection (not the source's).
 *
 * **Dry-run shape** per cli-design §6.4 group-duplicate variant:
 * minimal `{operation: "duplicate_group", board_id, group_id,
 * name?}`. No preflight read leg fires (Monday's `duplicate_group`
 * reports `not_found` if the IDs are bogus and the dry-run is
 * purely argv-derived — mirrors `column-delete`'s no-read pattern,
 * even though group-duplicate is non-destructive). `meta.source:
 * 'none'`.
 *
 * **Eager invalidation** (cli-design §8 single-leg call-site
 * contract). On success, calls `invalidateBoard(boardId)` AFTER
 * the success envelope's `data` projection completes. The cached
 * `groups: [...]` list grew by one entry, so subsequent reads in
 * the same process see the new group without TTL eviction.
 *
 * **Idempotent: false.** Every call creates a new group with a
 * fresh ID (mirrors `item duplicate` / `board duplicate`). NOT
 * destructive (no `--yes` gate).
 */
import { z } from 'zod';
import { ensureSubcommand, type CommandModule } from '../types.js';
import { emitDryRun, emitMutation } from '../emit.js';
import { resolveClient } from '../../api/resolve-client.js';
import { parseArgv } from '../parse-argv.js';
import { unwrapOrThrow } from '../../utils/parse-boundary.js';
import { BoardIdSchema, GroupIdSchema } from '../../types/ids.js';
import { withBoardInvalidationSingleLeg } from '../../api/board-mutation-invalidation.js';
import {
  GROUP_FIELDS_FRAGMENT,
  groupProjectionSchema,
  projectMutationGroup,
  type GroupProjection,
} from '../../api/group-mutation-result.js';
import { assertResponseFieldPresent } from '../../api/response-root.js';

const DUPLICATE_GROUP_MUTATION = `
  mutation GroupDuplicate(
    $boardId: ID!,
    $groupId: String!,
    $groupTitle: String
  ) {
    duplicate_group(
      board_id: $boardId,
      group_id: $groupId,
      group_title: $groupTitle
    ) {
      ${GROUP_FIELDS_FRAGMENT}
    }
  }
`;

export const boardGroupDuplicateOutputSchema = groupProjectionSchema;
export type BoardGroupDuplicateOutput = GroupProjection;

const inputSchema = z
  .object({
    boardId: BoardIdSchema,
    groupId: GroupIdSchema,
    name: z
      .string()
      .refine((s) => s.trim().length > 0, {
        message: '--name must be non-empty (whitespace-only is rejected)',
      })
      .optional(),
  })
  .strict();

const responseSchema = z
  .object({
    duplicate_group: z.unknown(),
  })
  .loose();

export const boardGroupDuplicateCommand: CommandModule<
  z.infer<typeof inputSchema>,
  BoardGroupDuplicateOutput
> = {
  name: 'board.group-duplicate',
  summary: 'Duplicate a group on a board',
  examples: [
    'monday board group-duplicate 12345 topics',
    'monday board group-duplicate 12345 topics --name "Topics (copy)"',
    'monday board group-duplicate 12345 topics --dry-run --json',
  ],
  // duplicate_group is non-idempotent — every call creates a new
  // group with a fresh ID (Monday auto-generates). Mirrors `item
  // duplicate` / `board duplicate` rationale.
  idempotent: false,
  inputSchema,
  outputSchema: boardGroupDuplicateOutputSchema,
  attach: (program, ctx) => {
    const noun = ensureSubcommand(program, 'board', 'Board commands');
    noun
      .command('group-duplicate <boardId> <groupId>')
      .description(boardGroupDuplicateCommand.summary)
      .option('--name <n>', "new group's title (maps to wire group_title; omitted → Monday's server-side default naming)")
      .addHelpText(
        'after',
        ['', 'Examples:', ...boardGroupDuplicateCommand.examples.map((e) => `  ${e}`), ''].join('\n'),
      )
      .action(async (boardId: unknown, groupId: unknown, opts: unknown) => {
        const parsed = parseArgv(boardGroupDuplicateCommand.inputSchema, {
          boardId,
          groupId,
          ...(opts as Readonly<Record<string, unknown>>),
        });
        const name = parsed.name?.trim();

        const { client, globalFlags, apiVersion, toEmit } = resolveClient(
          ctx,
          program.opts(),
        );

        if (globalFlags.dryRun) {
          // Per cli-design §6.4 group-duplicate variant: minimal
          // `{operation, board_id, group_id, name?}`. No preflight
          // read fires — purely argv-derived; meta.source: 'none'.
          // Mirrors column-delete's no-read pattern (Monday's
          // duplicate_group reports not_found server-side if IDs
          // are bogus — there's no preview value in a preflight
          // read because the CLI doesn't render the source group).
          const planned: Record<string, unknown> = {
            operation: 'duplicate_group',
            board_id: parsed.boardId,
            group_id: parsed.groupId,
          };
          if (name !== undefined) {
            planned.name = name;
          }
          emitDryRun({
            ctx,
            programOpts: program.opts(),
            plannedChanges: [planned],
            source: 'none',
            cacheAgeSeconds: null,
            warnings: [],
            apiVersion,
          });
          return;
        }

        // Live path. Send each optional arg only when the agent
        // provided one — passing `null` would explicitly clear /
        // reject Monday's server-side default naming.
        const variables: Record<string, unknown> = {
          boardId: parsed.boardId,
          groupId: parsed.groupId,
        };
        if (name !== undefined) {
          variables.groupTitle = name;
        }

        // §8 single-leg call-site contract via `withBoardInvalidation
        // SingleLeg` (R46): the helper invalidates AFTER the closure
        // returns (i.e. after `data` projection completes). On the
        // error path the closure's throw bypasses invalidation —
        // matching the §8 "skip on error" rule.
        const { data: projected, response } = await withBoardInvalidationSingleLeg({
          boardId: parsed.boardId,
          env: ctx.env,
          perform: async () => {
            const wireResponse = await client.raw<unknown>(
              DUPLICATE_GROUP_MUTATION,
              variables,
              { operationName: 'GroupDuplicate' },
            );
            const data = unwrapOrThrow(
              responseSchema.safeParse(wireResponse.data),
              {
                context: 'Monday returned a malformed GroupDuplicate response',
                details: { board_id: parsed.boardId, group_id: parsed.groupId },
                hint:
                  "this is a data-integrity error in Monday's response; " +
                  'verify the response shape and update responseSchema if ' +
                  "Monday's contract has changed.",
              },
            );
            // R42: consolidate the inline missing-key check.
            assertResponseFieldPresent({
              data,
              key: 'duplicate_group',
              operationLabel: 'GroupDuplicate',
              details: {
                board_id: parsed.boardId,
                group_id: parsed.groupId,
              },
              nullHandling: 'caller_handles',
            });
            // R48 lift: null-payload guard + projection. duplicate's
            // null path uses `not_found` (Monday's "source group id
            // bogus / no access" mapping).
            const projection = projectMutationGroup({
              raw: data.duplicate_group,
              errorCode: 'not_found',
              errorMessage: `Monday returned no group payload from duplicate_group for board ${parsed.boardId} group ${parsed.groupId}`,
              boardId: parsed.boardId,
              idKey: 'group_id',
              idValue: parsed.groupId,
            });
            return { data: projection, response: wireResponse };
          },
        });

        emitMutation({
          ctx,
          data: projected,
          schema: boardGroupDuplicateCommand.outputSchema,
          programOpts: program.opts(),
          warnings: [],
          ...toEmit(response),
          source: 'live',
          cacheAgeSeconds: null,
        });
      });
  },
};
