/**
 * Frozen ISO 3166-1 alpha-2 country code allowlist for the `phone`
 * column-value translator (`v0.2-plan.md` §3 M8). Source-of-truth
 * lifted into its own module so the data + the membership test stay
 * one import away from `phones.ts` without bloating that file's
 * grammar concerns.
 *
 * **Why a frozen list rather than `Intl`.** Node's `Intl` exposes
 * `Intl.supportedValuesOf('region')` (Node 18+), which returns the
 * full ISO 3166-1 alpha-2 code set the runtime knows about. The
 * problem: the set the runtime knows about is ICU-version-dependent,
 * so a CLI that builds against Node 22 may accept a code on a
 * developer's machine and reject it on a CI runner. A frozen
 * allowlist is reproducible across runtimes and the file is
 * regenerated by hand when ISO publishes a new code (rare — the
 * 3166-1 list grows by ~one entry per decade).
 *
 * **Source of the list.** ISO 3166-1 alpha-2 as of 2025-01 (vendored
 * from Wikipedia's "ISO 3166-1 alpha-2" article cross-checked with
 * the ISO online browsing platform). Officially-assigned codes only
 * — exceptionally-reserved (`UK`, `EU`), transitional (`CS`), and
 * user-assigned (`AA`, `OO`) ranges are excluded. Monday's phone
 * validation accepts officially-assigned codes only per the
 * developer-portal phone-column reference.
 */

/**
 * Officially-assigned ISO 3166-1 alpha-2 country codes (uppercase).
 * Used by `parsePhoneInput` to validate the `<country>` segment of
 * the pipe-form `<phone>|<country>` input. Frozen `as const` so the
 * type narrows to a finite literal-string union; the `Set` form
 * below provides O(1) membership lookup.
 *
 * 249 codes (ISO 3166-1 alpha-2 list count, 2025-01).
 */
export const ISO_3166_1_ALPHA_2_CODES = [
  'AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR',
  'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE',
  'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ',
  'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD',
  'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR',
  'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM',
  'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI',
  'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF',
  'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS',
  'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU',
  'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT',
  'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN',
  'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK',
  'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME',
  'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ',
  'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA',
  'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU',
  'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM',
  'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS',
  'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI',
  'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV',
  'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK',
  'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA',
  'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI',
  'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW',
] as const;

export type IsoCountryCode = (typeof ISO_3166_1_ALPHA_2_CODES)[number];

const ISO_CODE_SET: ReadonlySet<string> = new Set<string>(
  ISO_3166_1_ALPHA_2_CODES,
);

/**
 * Membership test against the frozen allowlist. Case-sensitive —
 * Monday's phone-column validation expects uppercase, so the caller
 * uppercases before calling. The narrowing to `IsoCountryCode` lets
 * downstream code that wants to enumerate codes use the literal
 * union without re-validating.
 */
export const isIsoCountryCode = (code: string): code is IsoCountryCode =>
  ISO_CODE_SET.has(code);
